name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            mkdir -p ${{ secrets.SERVER_DEPLOY_PATH }}
            cd ${{ secrets.SERVER_DEPLOY_PATH }}

            npm install -g pm2
            PM2_BIN=$(which pm2)
            echo "PM2_BIN: $PM2_BIN"
            export PATH="$HOME/.local/share/pnpm:$PATH"
            
            APP_NAME="webp"
            $PM2_BIN stop "$APP_NAME" || true
            $PM2_BIN delete "$APP_NAME" || true

            echo "ğŸ“¦ ìµœì‹  ì½”ë“œ ê°€ì ¸ì˜¤ëŠ” ì¤‘..."
            git clone ${{ vars.REPO_URL }} . || git pull origin main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            echo "ğŸ“¦ ì˜ì¡´ì„± ì„¤ì¹˜ ì¤‘..."
            pnpm install

            echo "ğŸ—ï¸ ë¹Œë“œ ì¤‘..."
            pnpm run build || exit 1

            echo "ğŸš€ ìƒˆ ì„œë²„ ì‹¤í–‰ ì¤‘..."
            $PM2_BIN start pnpm --name "$APP_NAME" -- start

            echo "âœ… ë°°í¬ ì™„ë£Œ"
