name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "ðŸ” ê¸°ì¡´ Next.js ì„œë²„ ì¢…ë£Œ ì¤‘..."
            pkill -f "next start" || true
            pkill -f "node.*.next" || true
            pkill -f "node.*server.js" || true
            sleep 3
            echo "âœ… ê¸°ì¡´ ì„œë²„ ì¢…ë£Œ ì™„ë£Œ"


            mkdir -p ${{ secrets.SERVER_DEPLOY_PATH }}
            cd ${{ secrets.SERVER_DEPLOY_PATH }}

            echo "ðŸ“¦ ìµœì‹  ì½”ë“œ ê°€ì ¸ì˜¤ëŠ” ì¤‘..."
            git clone ${{ vars.REPO_URL }} . || git pull origin main
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PNPM_HOME="$HOME/.local/share/pnpm"
            export PATH="$PNPM_HOME:$PATH"

            echo "ðŸ“¦ ì˜ì¡´ì„± ì„¤ì¹˜ ì¤‘..."
            pnpm install

            echo "ðŸ—ï¸ ë¹Œë“œ ì¤‘..."
            pnpm run build

            echo "ðŸš€ ìƒˆ ì„œë²„ ì‹¤í–‰ ì¤‘..."
            nohup pnpm run start > output.log 2>&1 &
            sleep 1

            PID=$(pgrep -f "next start" | head -n 1)
            echo "âœ… ìƒˆ ì„œë²„ ì‹¤í–‰ ì™„ë£Œ (PID: $PID)"

